package com.doubeye.spider.content.analyzer.chinaHr.dictionary;
import net.sf.json.JSONArray;
/**
 * @author doubeye
 * @version 1.0.0
 * 定义中华英才网中所有字典的常量
This class is auto-generated by tool ConstantClassHelper(developed by doubeye(doubeye@sina.com))
 */
public class ChinaHrDictionary {
	/**
	 * 城市
	 */
	public static final JSONArray CHINA_HR_CITY = JSONArray.fromObject("[{\"id\":\"18\",\"name\":\"安徽\"},{\"id\":\"44\",\"name\":\"澳门特别行政区\"},{\"id\":\"34\",\"name\":\"北京\"},{\"id\":\"37\",\"name\":\"重庆\"},{\"id\":\"19\",\"name\":\"福建\"},{\"id\":\"31\",\"name\":\"甘肃\"},{\"id\":\"25\",\"name\":\"广东\"},{\"id\":\"38\",\"name\":\"广西壮族自治区\"},{\"id\":\"28\",\"name\":\"贵州\"},{\"id\":\"26\",\"name\":\"海南\"},{\"id\":\"45\",\"name\":\"海外\"},{\"id\":\"11\",\"name\":\"河北\"},{\"id\":\"22\",\"name\":\"河南\"},{\"id\":\"15\",\"name\":\"黑龙江\"},{\"id\":\"23\",\"name\":\"湖北\"},{\"id\":\"24\",\"name\":\"湖南\"},{\"id\":\"14\",\"name\":\"吉林\"},{\"id\":\"16\",\"name\":\"江苏\"},{\"id\":\"20\",\"name\":\"江西\"},{\"id\":\"13\",\"name\":\"辽宁\"},{\"id\":\"39\",\"name\":\"内蒙古自治区\"},{\"id\":\"41\",\"name\":\"宁夏回族自治区\"},{\"id\":\"32\",\"name\":\"青海\"},{\"id\":\"21\",\"name\":\"山东\"},{\"id\":\"30\",\"name\":\"陕西\"},{\"id\":\"12\",\"name\":\"山西\"},{\"id\":\"36\",\"name\":\"上海\"},{\"id\":\"27\",\"name\":\"四川\"},{\"id\":\"33\",\"name\":\"台湾\"},{\"id\":\"35\",\"name\":\"天津\"},{\"id\":\"40\",\"name\":\"西藏自治区\"},{\"id\":\"43\",\"name\":\"香港特别行政区\"},{\"id\":\"42\",\"name\":\"新疆维吾尔自治区\"},{\"id\":\"29\",\"name\":\"云南\"},{\"id\":\"17\",\"name\":\"浙江\"}]");

	/**
	 * 学历
	 */
	public static final JSONArray CHINA_HR_DEGREE = JSONArray.fromObject("[{\"id\":\"0\",\"name\":\"不限\"},{\"id\":\"1\",\"name\":\"博士\"},{\"id\":\"2\",\"name\":\"EMBA\"},{\"id\":\"3\",\"name\":\"MBA\"},{\"id\":\"4\",\"name\":\"硕士\"},{\"id\":\"5\",\"name\":\"本科\"},{\"id\":\"6\",\"name\":\"大专\"},{\"id\":\"7\",\"name\":\"高职\"},{\"id\":\"8\",\"name\":\"高中\"},{\"id\":\"9\",\"name\":\"职高\"},{\"id\":\"10\",\"name\":\"中专\"},{\"id\":\"11\",\"name\":\"中职\"},{\"id\":\"12\",\"name\":\"中技\"},{\"id\":\"13\",\"name\":\"初中\"},{\"id\":\"14\",\"name\":\"其他\"}]");

	/**
	 * 公司类型
	 */
	public static final JSONArray CHINA_HR_COMPANY_TYPE = JSONArray.fromObject("[{\"id\":\"0\",\"name\":\"全部\"},{\"id\":\"1\",\"name\":\"外商独资\"},{\"id\":\"2\",\"name\":\"合资\"},{\"id\":\"3\",\"name\":\"上市公司\"},{\"id\":\"4\",\"name\":\"国企\"},{\"id\":\"5\",\"name\":\"国家机关\"},{\"id\":\"6\",\"name\":\"事业单位\"},{\"id\":\"7\",\"name\":\"民企/私企\"},{\"id\":\"8\",\"name\":\"代表处\"},{\"id\":\"9\",\"name\":\"非赢利组织\"},{\"id\":\"10\",\"name\":\"股份制\"},{\"id\":\"11\",\"name\":\"其他\"}]");

	/**
	 * 公司规模
	 */
	public static final JSONArray CHINA_HR_COMPANY_SIZE = JSONArray.fromObject("[{\"id\":\"0\",\"name\":\"全部\"},{\"id\":\"1\",\"name\":\"20人以下\"},{\"id\":\"2\",\"name\":\"21-50人\"},{\"id\":\"3\",\"name\":\"51-100人\"},{\"id\":\"4\",\"name\":\"101-300人\"},{\"id\":\"5\",\"name\":\"301-500人\"},{\"id\":\"6\",\"name\":\"500人以上\"}]");

	/**
	 * 经验
	 */
	public static final JSONArray CHINA_HR_EXPERIENCE = JSONArray.fromObject("[{\"id\":\"0\",\"name\":\"不限\"},{\"id\":\"1\",\"name\":\"应届毕业生\"},{\"id\":\"2\",\"name\":\"1年以下\"},{\"id\":\"3\",\"name\":\"1-3年\"},{\"id\":\"4\",\"name\":\"3-5年\"},{\"id\":\"5\",\"name\":\"5-7年\"},{\"id\":\"6\",\"name\":\"7-10年\"},{\"id\":\"7\",\"name\":\"10年以上\"}]");

	/**
	 * 经验
	 */
	public static final JSONArray CHINA_HR_JOB_PROPERTY = JSONArray.fromObject("[{\"id\":\"0\",\"name\":\"全部\"},{\"id\":\"1\",\"name\":\"全职\"},{\"id\":\"2\",\"name\":\"兼职\"},{\"id\":\"3\",\"name\":\"实习\"}]");

}