package com.doubeye.core.systemProperties;
/**
 * @author doubeye
 * @version 1.0.0
 * 定义所有系统属性名称的常量
This class is auto-generated by tool ConstantClassHelper(developed by doubeye(doubeye@sina.com))
 */
public class SystemPropertiesConstant {
	/**
	 * 默认时间日期格式
	 */
	public static final String SYSTEM_PROPERTY_DEFAULT_TIME_FORMAT = "DEFAULT_TIME_FORMAT";

	/**
	 * 环境版本号
	 */
	public static final String SYSTEM_PROPERTY_ENV_VERSION = "ENV_VERSION";

	/**
	 * LDAP登录认证时用户名的域名
	 */
	public static final String SYSTEM_PROPERTY_LDAP_DOMAIN_NAME = "LDAP_DOMAIN_NAME";

	/**
	 * 生成TOKEN的密钥
	 */
	public static final String SYSTEM_PROPERTY_TOKEN_SECRET_KEY = "TOKEN_SECRET_KEY";

}